version: "2"
services:
  mariadb:
      image: mariadb
      container_name: mariadb
      environment:
          - MYSQL_ROOT_PASSWORD=project
          - MYSQL_DATABASE=BroadReach
      ports:
          - 3306:3306  
      volumes:
          - database:/var/lib/mysql
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      environment:
          - PMA_ARBITRARY=1
          - PMA_HOST=mariadb
      restart: always
      ports:
          - 8080:80
      volumes:
          - /sessions
      links:
          - mariadb
  frontend:
      image: webdevops/php-apache
      container_name: frontend
      ports:
        - 8000:80
      volumes:
        - ./:/app/
      links:
        - mariadb

volumes: 
    database: {}